### ISSUE TITLE
Lab Report 1 Feedback

### ISSUE THREAD

**Issue by jesslam948** [theojouvin/CSE15L#2]
Here is your feedback for Lab Report 1:

- [x] All relevant URLs written as markdown links
- [x] All relevant code examples written with backticks (```)
- [x] All screenshots correspond to the described steps
- [x] All titles of sections are formatted as headers or similar
- [x] Lab report is on its own page, not the index page
- [x] Last example shows how to run remotely saving time
- [x] Text is formatted in a way that was easy for grader to read

Additional comments from your grader:
Great job on your lab report! It is sooooo well written and I loved how you added some extra features such as the favicon (I'm assuming it's your initials?) and the little 'spoiler' type tags that hide the images until we click on them :DD
![image](https://user-images.githubusercontent.com/22829218/163321681-a717c30f-18b4-4133-83a0-5b58d2d48026.png)

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by theojouvin** [comment]
Not sure if you'll see this, but thank you so much!!
Yes, the favicon has my initials.
I like those spoilers too, but they're quite a headache! HTML breaks Markdown formatting. Realistically, I would have the spoilers interspersed in the numbered lists, but those lists would break if I did that, so I had to put them at the end.

Thanks again!
